["info"]
name = "game-of-life"
description = "A starknet implementation of Conway's Game Of Life"
license = "MIT"
version = "0.0.1-alpha"
authors = [
    "wojciech.szymczyk@swmansion.com", "perama-v"
]

["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["contracts", "./lib/cairo_contracts/src"]

["protostar.contracts"]
gol = [
    "contracts/gol.cairo",
]
proxy = [
    "lib/cairo_contracts/src/openzeppelin/upgrades/Proxy.cairo",
]

[profile.devnet.protostar.deploy]
gateway-url="http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"

[profile.mainnet.protostar.deploy]
network="alpha-mainnet"
