version: '3'

services:
  db:
    environment:
      POSTGRES_USER: indexer-user
      POSTGRES_DB: indexer-db
      POSTGRES_PASSWORD: indexer-password
    image: postgres:14-alpine
    ports:
      - "5432:5432"
